# Generated by Django 4.2.16 on 2025-04-10 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=256)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], max_length=30)),
            ],
        ),
    ]
