# Generated by Django 4.2.16 on 2025-04-13 01:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AddField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
