# Generated by Django 4.2.16 on 2025-04-09 22:03

import apps.bawls.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoalitionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logoUrl', models.TextField()),
                ('websiteUrl', models.TextField()),
                ('thumbnail', models.ImageField(upload_to=apps.bawls.models.rwi_thumbnail_directory)),
                ('blockchain', models.CharField(max_length=200)),
                ('narrative', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=20)),
                ('logoUrl', models.TextField()),
                ('thumbnail', models.ImageField(upload_to=apps.bawls.models.gallery_thumbnail_directory)),
                ('columns', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('rows', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
