# Generated by Django 4.2.16 on 2025-04-09 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bawls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coalitionmember',
            options={'ordering': ['-name', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-title', '-created_at']},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
