# Generated by Django 4.2.16 on 2025-04-10 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bawls', '0003_alter_coalitionmember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coalitionmember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='coalitionmember',
            name='logoUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='logoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
