# Generated by Django 4.2.16 on 2025-04-10 21:38

import apps.bawls.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawls', '0004_alter_coalitionmember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to=apps.bawls.models.gallery_thumbnail_directory),
        ),
    ]
