# Generated by Django 4.2.16 on 2025-04-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('bawls', '0006_alter_coalitionmember_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coalitionmember',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coalition_thumbnail', to='media.media'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_thumbnail', to='media.media'),
        ),
    ]
